# -- (Optional) When using a custom network
# networks:
#   your-traefik-network:
#     external: true
services:
  traefik:
    image: docker.io/library/traefik:v3.1.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 172.17.0.1:7003:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    # networks:
    #   - your-traefik-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.farreljordan.com`)"
      - "traefik.http.routers.traefik.service=dashboard@internal"
      - "traefik.http.routers.traefik.middlewares=dashboard_redirect@internal,dashboard_stripprefix@internal"

      - "traefik.http.routers.traefik-api.entrypoints=web"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.farreljordan.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.traefik-api.service=api@internal"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
