version: '3'
services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"
      - "1943:443"
      - "1194:1194/udp"
    volumes:
      - ./openvpn_data:/openvpn  # Update this path to your actual data path
    restart: always
