version: '3'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en_US
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - PORT=51821
      - WG_PORT=51820
#      - WG_POST_UP='iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o docker0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT'
#      - WG_POST_DOWN='iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o docker0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT'
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
# web ui can be accessed 10.8.0.1 since the client default address is 10.8.0.x 
#      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    labels:
      # traefik
      - "traefik.enable=true"
      - "traefik.http.services.wireguardservice.loadbalancer.server.port=51821"
      # http to https
      - "traefik.http.routers.wireguard.service=wireguardservice"
      # ⚠️ Required:
      # Change this to your host's public address
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.farreljordan.com`)"
      - "traefik.http.routers.wireguard.entrypoints=web"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true
